name = "rag"
main = "src/index.ts"
compatibility_date = "2025-06-06"

[ai]
binding = "AI"

[vars]
ENABLE_TEXT_SPLITTING = true

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[d1_databases]]
binding = "DATABASE"
database_name = "docs-rag"
database_id = "25f146d1-925c-47de-8453-723abaa70ad6"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "docs-rag-index"

[[workflows]]
name = "rag"
binding = "RAG_WORKFLOW"
class_name = "RAGWorkflow"
